### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by zloybik** [asesidaa/TaikoLocalServer#12]
you can make a video tutorial on the text does not work, it is too unclear

**Comment by asesidaa** [comment]
Sorry, there won't be public video about this considering that the arcade version is still in operation.
If you feel something is unclear, feel free to ask in discord channel.

**Comment by zloybik** [comment]
hello thank you for answering my question I came here to ask for a link to your discord channel

**Comment by asesidaa** [comment]
> hello thank you for answering my question I came here to ask for a link to your discord channel

https://discord.gg/eFuZWJBe

**Comment by zloybik** [comment]
Hello again! Can you lend me the link to the discord server again

**Comment by asesidaa** [comment]
> Hello again! Can you lend me the link to the discord server again

https://discord.gg/ybwfqGjX
