### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by zloybik** [asesidaa/TaikoLocalServer#13]
what should I do if I've done everything I need to do, but the game just doesn't connect?
![Снимок экрана (244)](https://user-images.githubusercontent.com/106350231/204063652-d143f86d-df9b-4a5e-8d22-28f0b34af678.png)
![Снимок экрана (245)](https://user-images.githubusercontent.com/106350231/204063655-c8814b13-b270-4754-a11d-ae4ac80e5807.png)

**Comment by fuzyak3r** [comment]
brainrot
