### ISSUE TITLE
Game Server Error

### ISSUE THREAD

**Issue by babytaikoer** [asesidaa/TaikoLocalServer#16]
![image](https://user-images.githubusercontent.com/122341094/218307726-9362fe9a-d697-44f4-8354-62ee29efd2a8.png)
what should i do

**Comment by asesidaa** [comment]
Hi, for setup issues, you can ask in discord channel https://discord.gg/GdPzPVZK

**Comment by kinnounko** [comment]
> Hi, for setup issues, you can ask in discord channel https://discord.gg/GdPzPVZK

Hey there, sorry for necroing this thread, is there any way to contact you? I'm interested in this project.

Thanks
Väinö

**Comment by asesidaa** [comment]
> > Hi, for setup issues, you can ask in discord channel https://discord.gg/GdPzPVZK
> 
> Hey there, sorry for necroing this thread, is there any way to contact you? I'm interested in this project.
> 
> Thanks Väinö

You can discuss (and seek for help) in discord https://discord.gg/Yqwgs9ur

**Comment by kinnounko** [comment]
Thank you very much. ^ ^

**Comment by ShikyC** [comment]
Can I get a DC invitation link also? I'm willing to contribute
