### ISSUE TITLE
Configuring for production environment

### ISSUE THREAD

**Issue by komikazui** [asesidaa/TaikoLocalServer#18]
I was looking to see if it was possible to run in a production environment. Will a guide be written to set up?

**Comment by asesidaa** [comment]
There will not be a guide, as this is not meant for any kind of production purpose, it’s just for ease of use in a local environment like most other servers.

However, even with default configs, there’s really nothing preventing you from connecting from another machine. You can also experiment with things like a reverse proxy for https as long as you have the experience.
