### ISSUE TITLE
Error happen when AccessCode is some value?

### ISSUE THREAD

**Issue by HelloworldDk** [asesidaa/TaikoLocalServer#27]
when i use my own banapassport to login,the server throw a error,and makes game crash
the log is in the picture i uploaded
![JU5HN{J}BKY_25 $CI08 IA](https://github.com/asesidaa/TaikoLocalServer/assets/142757958/174aec7b-be40-4635-83d4-f8577964f214)
you can just try this accesscode:00000000016191807923
or this cards.dat(use TAL and press 'P')
```
00000000016191807923000000000006710109760000000000000000000000000250BB8800000000000000000000000017D672C4

```
it happens on tons of cards.i think all official cards may crush on this error,hope you can solve it!
(tried my card with official card reader(Card IF PCB from Arcade),crash happens also)

**Comment by asesidaa** [comment]
Hi, this error is normal and is just for logging  purpose 
Crashes are normally caused by other reasons. For example, if you have omnimix installed, you need to make sure both server and game are properly configured.
Join the discord server for more discussion https://discord.gg/8Y2en2fn

**Comment by HelloworldDk** [comment]
> Hi, this error is normal and is just for logging purpose Crashes are normally caused by other reasons. For example, if you have omnimix installed, you need to make sure both server and game are properly configured. Join the discord server for more discussion https://discord.gg/8Y2en2fn

I tried accesscode:000000000[0]6191807923 and it works fine without any crashes and errors,but000000000[1]6191807923 does make error and crash.My game has no modification,no omnimix,it's just an originial game.
Is this really just my problem?
I joined the server and made self introduction but didn't get a member access.
![image](https://github.com/asesidaa/TaikoLocalServer/assets/142757958/3d846230-88aa-4f4a-bea7-1878561a6786)
