### ISSUE TITLE
Music file not found but present

### ISSUE THREAD

**Issue by Alidonis** [asesidaa/TaikoLocalServer#28]
In my logs file, the only exception present is 
`System.IO.FileNotFoundException: Music info file not found!`

However it is CLEARLY present
![image](https://github.com/asesidaa/TaikoLocalServer/assets/64419217/77d2d8ee-d2d1-4a52-9cf3-c548e0e45ec7)

for some reason, GameDataService.cs: 193 does not find the proper music path.

**Comment by asesidaa** [comment]
Current master branch contains old readme for 0818, please refer to the readme in the refactor branch
If you are playing 0818, use the 0.3.0 release

**Comment by Alidonis** [comment]
![image](https://github.com/asesidaa/TaikoLocalServer/assets/64419217/27f8dc94-0b9d-4ee0-b689-ef2959e80404)
It seems there is a cryptography problem

Also, I am not sure how to check my taiko version...

**Comment by asesidaa** [comment]
Depending on where you get the game
https://github.com/asesidaa/TaikoLocalServer/releases/tag/v0.3.0 this is for 0818
Newer versions of server are for 3209(CHN)

If you can directly extract json files from .bin files, it's either 0018 or 0818. The server only supports 0818

**Comment by Alidonis** [comment]
what differentiates 0018 and 0818?

**Comment by asesidaa** [comment]
Try put taiko.exe here https://mon.im/bemanipatcher/taikonotatsujin.html and check which one matches

**Comment by Alidonis** [comment]
thank you so much for the help!
